// Code generated by protoc-gen-go. DO NOT EDIT.
// source: import/intent.proto

package _import

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	common "shitty.moe/satelit-project/satelit-scraper/proto/common"
	data "shitty.moe/satelit-project/satelit-scraper/proto/data"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Asks to import anime titles index and schedule new titles for scraping
type ImportIntent struct {
	// Intent ID
	Id *common.UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// External data source to which index files belongs to
	Source data.Source `protobuf:"varint,2,opt,name=source,proto3,enum=data.Source" json:"source,omitempty"`
	// URL of latest anime titles index
	NewIndexUrl string `protobuf:"bytes,3,opt,name=new_index_url,json=newIndexUrl,proto3" json:"new_index_url,omitempty"`
	// URL of previous anime titles index
	OldIndexUrl string `protobuf:"bytes,4,opt,name=old_index_url,json=oldIndexUrl,proto3" json:"old_index_url,omitempty"`
	// Identifiers of anime titles that should be re-imported
	ReimportIds          []int32  `protobuf:"zigzag32,5,rep,packed,name=reimport_ids,json=reimportIds,proto3" json:"reimport_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportIntent) Reset()         { *m = ImportIntent{} }
func (m *ImportIntent) String() string { return proto.CompactTextString(m) }
func (*ImportIntent) ProtoMessage()    {}
func (*ImportIntent) Descriptor() ([]byte, []int) {
	return fileDescriptor_93c332ae50efc1f8, []int{0}
}

func (m *ImportIntent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportIntent.Unmarshal(m, b)
}
func (m *ImportIntent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportIntent.Marshal(b, m, deterministic)
}
func (m *ImportIntent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportIntent.Merge(m, src)
}
func (m *ImportIntent) XXX_Size() int {
	return xxx_messageInfo_ImportIntent.Size(m)
}
func (m *ImportIntent) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportIntent.DiscardUnknown(m)
}

var xxx_messageInfo_ImportIntent proto.InternalMessageInfo

func (m *ImportIntent) GetId() *common.UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ImportIntent) GetSource() data.Source {
	if m != nil {
		return m.Source
	}
	return data.Source_UNKNOWN
}

func (m *ImportIntent) GetNewIndexUrl() string {
	if m != nil {
		return m.NewIndexUrl
	}
	return ""
}

func (m *ImportIntent) GetOldIndexUrl() string {
	if m != nil {
		return m.OldIndexUrl
	}
	return ""
}

func (m *ImportIntent) GetReimportIds() []int32 {
	if m != nil {
		return m.ReimportIds
	}
	return nil
}

type ImportIntentResult struct {
	// Intent ID
	Id *common.UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// IDs of anime titles that was not imported
	SkippedIds           []int32  `protobuf:"zigzag32,2,rep,packed,name=skipped_ids,json=skippedIds,proto3" json:"skipped_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportIntentResult) Reset()         { *m = ImportIntentResult{} }
func (m *ImportIntentResult) String() string { return proto.CompactTextString(m) }
func (*ImportIntentResult) ProtoMessage()    {}
func (*ImportIntentResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_93c332ae50efc1f8, []int{1}
}

func (m *ImportIntentResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportIntentResult.Unmarshal(m, b)
}
func (m *ImportIntentResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportIntentResult.Marshal(b, m, deterministic)
}
func (m *ImportIntentResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportIntentResult.Merge(m, src)
}
func (m *ImportIntentResult) XXX_Size() int {
	return xxx_messageInfo_ImportIntentResult.Size(m)
}
func (m *ImportIntentResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportIntentResult.DiscardUnknown(m)
}

var xxx_messageInfo_ImportIntentResult proto.InternalMessageInfo

func (m *ImportIntentResult) GetId() *common.UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ImportIntentResult) GetSkippedIds() []int32 {
	if m != nil {
		return m.SkippedIds
	}
	return nil
}

func init() {
	proto.RegisterType((*ImportIntent)(nil), "import.ImportIntent")
	proto.RegisterType((*ImportIntentResult)(nil), "import.ImportIntentResult")
}

func init() {
	proto.RegisterFile("import/intent.proto", fileDescriptor_93c332ae50efc1f8)
}

var fileDescriptor_93c332ae50efc1f8 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xe5, 0x14, 0x22, 0x71, 0x13, 0x90, 0x62, 0x96, 0x28, 0x0b, 0x21, 0x62, 0xc8, 0x94,
	0x48, 0xe5, 0x15, 0x58, 0x3c, 0x62, 0x94, 0x39, 0x2a, 0xbd, 0x1e, 0x2c, 0x1c, 0x3b, 0xf2, 0x8f,
	0xca, 0xbb, 0xf1, 0x72, 0x28, 0x76, 0x41, 0x9d, 0xba, 0x7e, 0xf7, 0x9c, 0x4f, 0x3e, 0x86, 0x47,
	0xb9, 0xac, 0xc6, 0xfa, 0x51, 0x6a, 0x2f, 0xb4, 0x1f, 0x56, 0x6b, 0xbc, 0xa1, 0x79, 0x82, 0x4d,
	0x75, 0x34, 0xcb, 0x62, 0xf4, 0x18, 0x82, 0xc4, 0x74, 0x6a, 0x2a, 0x3c, 0xf8, 0xc3, 0xe8, 0x4c,
	0xb0, 0x47, 0x91, 0x50, 0xf7, 0x43, 0xa0, 0x64, 0xb1, 0xc0, 0xa2, 0x84, 0x36, 0x90, 0x49, 0xac,
	0x49, 0x4b, 0xfa, 0x62, 0x0f, 0x43, 0x2c, 0x4f, 0x13, 0x7b, 0xe3, 0x99, 0x44, 0xfa, 0x02, 0x79,
	0x2a, 0xd7, 0x59, 0x4b, 0xfa, 0x87, 0x7d, 0x39, 0x6c, 0xc2, 0xe1, 0x23, 0x32, 0x7e, 0xbe, 0xd1,
	0x0e, 0xee, 0xb5, 0x38, 0xcd, 0x52, 0xa3, 0xf8, 0x9e, 0x83, 0x55, 0xf5, 0xae, 0x25, 0xfd, 0x1d,
	0x2f, 0xb4, 0x38, 0xb1, 0x8d, 0x4d, 0x56, 0x6d, 0x19, 0xa3, 0xf0, 0x22, 0x73, 0x93, 0x32, 0x46,
	0xe1, 0x7f, 0xe6, 0x19, 0x4a, 0x2b, 0xd2, 0x98, 0x59, 0xa2, 0xab, 0x6f, 0xdb, 0x5d, 0x5f, 0xf1,
	0xe2, 0x8f, 0x31, 0x74, 0xdd, 0x3b, 0xd0, 0xcb, 0xc7, 0x73, 0xe1, 0x82, 0xba, 0x3e, 0xe1, 0x09,
	0x0a, 0xf7, 0x25, 0xd7, 0x55, 0x60, 0x74, 0x66, 0xd1, 0x09, 0x67, 0xc4, 0xd0, 0x7d, 0xe6, 0xf1,
	0x5f, 0x5e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x57, 0xfb, 0x75, 0x47, 0x5c, 0x01, 0x00, 0x00,
}
