// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scraping/task.proto

package scraping

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	data "satelit-project/satelit-scraper/pkg/proto/data"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Represents a task for anime pages scraping
type Task struct {
	// Task ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// External DB from where to scrape info
	Source data.Source `protobuf:"varint,2,opt,name=source,proto3,enum=data.Source" json:"source,omitempty"`
	// Schedule IDs for each anime ID
	ScheduleIds []int32 `protobuf:"zigzag32,3,rep,packed,name=schedule_ids,json=scheduleIds,proto3" json:"schedule_ids,omitempty"`
	// Anime ID's to scrape
	AnimeIds             []int32  `protobuf:"zigzag32,4,rep,packed,name=anime_ids,json=animeIds,proto3" json:"anime_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f65971c76f182a, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetSource() data.Source {
	if m != nil {
		return m.Source
	}
	return data.Source_UNKNOWN
}

func (m *Task) GetScheduleIds() []int32 {
	if m != nil {
		return m.ScheduleIds
	}
	return nil
}

func (m *Task) GetAnimeIds() []int32 {
	if m != nil {
		return m.AnimeIds
	}
	return nil
}

// Scrape task creation request
type TaskCreate struct {
	// Maximum number of entities to scrape
	Limit int32 `protobuf:"zigzag32,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// External data source to scrape data from
	Source               data.Source `protobuf:"varint,2,opt,name=source,proto3,enum=data.Source" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TaskCreate) Reset()         { *m = TaskCreate{} }
func (m *TaskCreate) String() string { return proto.CompactTextString(m) }
func (*TaskCreate) ProtoMessage()    {}
func (*TaskCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f65971c76f182a, []int{1}
}

func (m *TaskCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskCreate.Unmarshal(m, b)
}
func (m *TaskCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskCreate.Marshal(b, m, deterministic)
}
func (m *TaskCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskCreate.Merge(m, src)
}
func (m *TaskCreate) XXX_Size() int {
	return xxx_messageInfo_TaskCreate.Size(m)
}
func (m *TaskCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskCreate.DiscardUnknown(m)
}

var xxx_messageInfo_TaskCreate proto.InternalMessageInfo

func (m *TaskCreate) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *TaskCreate) GetSource() data.Source {
	if m != nil {
		return m.Source
	}
	return data.Source_UNKNOWN
}

// Intermediate result of a parse task
type TaskYield struct {
	// ID of the related task
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// ID of the schedule
	ScheduleId int32 `protobuf:"zigzag32,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	// Parsed anime entity
	Anime                *data.Anime `protobuf:"bytes,3,opt,name=anime,proto3" json:"anime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TaskYield) Reset()         { *m = TaskYield{} }
func (m *TaskYield) String() string { return proto.CompactTextString(m) }
func (*TaskYield) ProtoMessage()    {}
func (*TaskYield) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f65971c76f182a, []int{2}
}

func (m *TaskYield) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskYield.Unmarshal(m, b)
}
func (m *TaskYield) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskYield.Marshal(b, m, deterministic)
}
func (m *TaskYield) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskYield.Merge(m, src)
}
func (m *TaskYield) XXX_Size() int {
	return xxx_messageInfo_TaskYield.Size(m)
}
func (m *TaskYield) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskYield.DiscardUnknown(m)
}

var xxx_messageInfo_TaskYield proto.InternalMessageInfo

func (m *TaskYield) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *TaskYield) GetScheduleId() int32 {
	if m != nil {
		return m.ScheduleId
	}
	return 0
}

func (m *TaskYield) GetAnime() *data.Anime {
	if m != nil {
		return m.Anime
	}
	return nil
}

// Signals that a task has been finished
type TaskFinish struct {
	// ID of the related task
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskFinish) Reset()         { *m = TaskFinish{} }
func (m *TaskFinish) String() string { return proto.CompactTextString(m) }
func (*TaskFinish) ProtoMessage()    {}
func (*TaskFinish) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f65971c76f182a, []int{3}
}

func (m *TaskFinish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskFinish.Unmarshal(m, b)
}
func (m *TaskFinish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskFinish.Marshal(b, m, deterministic)
}
func (m *TaskFinish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskFinish.Merge(m, src)
}
func (m *TaskFinish) XXX_Size() int {
	return xxx_messageInfo_TaskFinish.Size(m)
}
func (m *TaskFinish) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskFinish.DiscardUnknown(m)
}

var xxx_messageInfo_TaskFinish proto.InternalMessageInfo

func (m *TaskFinish) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func init() {
	proto.RegisterType((*Task)(nil), "scraping.Task")
	proto.RegisterType((*TaskCreate)(nil), "scraping.TaskCreate")
	proto.RegisterType((*TaskYield)(nil), "scraping.TaskYield")
	proto.RegisterType((*TaskFinish)(nil), "scraping.TaskFinish")
}

func init() { proto.RegisterFile("scraping/task.proto", fileDescriptor_69f65971c76f182a) }

var fileDescriptor_69f65971c76f182a = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x03, 0xb4, 0x58, 0x86, 0xa6, 0x91, 0xd5, 0x44, 0x52, 0x0f, 0x52, 0xa2, 0x09, 0x27,
	0x9a, 0xd4, 0x27, 0x30, 0x26, 0x46, 0xae, 0xab, 0x17, 0x4f, 0xcd, 0xca, 0x6e, 0x64, 0x52, 0x0a,
	0x0d, 0xbb, 0xbd, 0xf9, 0xf0, 0x66, 0x67, 0x8b, 0x7a, 0x31, 0xf1, 0x38, 0xdf, 0x0f, 0xf3, 0x7f,
	0x3b, 0x70, 0xa1, 0xeb, 0x41, 0x1c, 0xb0, 0xfb, 0x58, 0x1b, 0xa1, 0x77, 0xe5, 0x61, 0xe8, 0x4d,
	0xcf, 0x66, 0x23, 0x5c, 0x9e, 0x4b, 0x61, 0xc4, 0x5a, 0x74, 0xb8, 0x57, 0x2e, 0x5b, 0x26, 0x44,
	0x74, 0x7f, 0x1c, 0xea, 0x13, 0xca, 0x3f, 0x61, 0xf2, 0x2a, 0xf4, 0x8e, 0x2d, 0xc0, 0x47, 0x99,
	0x7a, 0x99, 0x57, 0x44, 0xdc, 0x47, 0xc9, 0x6e, 0x21, 0x74, 0xdf, 0xa5, 0x7e, 0xe6, 0x15, 0x8b,
	0xcd, 0xbc, 0xb4, 0xff, 0x96, 0x2f, 0xc4, 0xf8, 0x29, 0x63, 0x2b, 0x98, 0xeb, 0xba, 0x51, 0xf2,
	0xd8, 0xaa, 0x2d, 0x4a, 0x9d, 0x06, 0x59, 0x50, 0x24, 0x3c, 0x1e, 0x59, 0x25, 0x35, 0xbb, 0x86,
	0x88, 0x14, 0x28, 0x9f, 0x50, 0x3e, 0x23, 0x50, 0x49, 0x9d, 0x3f, 0x03, 0xd8, 0xf6, 0xc7, 0x41,
	0x09, 0xa3, 0xd8, 0x25, 0x4c, 0x5b, 0xdc, 0xa3, 0x21, 0x8d, 0x84, 0xbb, 0xe1, 0x7f, 0x26, 0x79,
	0x03, 0x91, 0xdd, 0xf4, 0x86, 0xaa, 0x95, 0xec, 0x0a, 0xce, 0xec, 0x45, 0xb6, 0xdf, 0x2f, 0x0a,
	0xed, 0x58, 0x49, 0x76, 0x03, 0xf1, 0x2f, 0x5f, 0x5a, 0x98, 0x70, 0xf8, 0xd1, 0x65, 0x2b, 0x98,
	0x92, 0x5c, 0x1a, 0x64, 0x5e, 0x11, 0x6f, 0x62, 0xd7, 0xf5, 0x60, 0x11, 0x77, 0x49, 0x7e, 0xe7,
	0x9c, 0x9f, 0xb0, 0x43, 0xdd, 0xfc, 0x59, 0xf5, 0x1e, 0xd2, 0x7d, 0xef, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x96, 0x5c, 0xb0, 0xbc, 0xa5, 0x01, 0x00, 0x00,
}
