// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scraper/intent.proto

package scraper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// External DB
type ScrapeIntent_Source int32

const (
	ScrapeIntent_UNKNOWN ScrapeIntent_Source = 0
	ScrapeIntent_ANIDB   ScrapeIntent_Source = 1
)

var ScrapeIntent_Source_name = map[int32]string{
	0: "UNKNOWN",
	1: "ANIDB",
}

var ScrapeIntent_Source_value = map[string]int32{
	"UNKNOWN": 0,
	"ANIDB":   1,
}

func (x ScrapeIntent_Source) String() string {
	return proto.EnumName(ScrapeIntent_Source_name, int32(x))
}

func (ScrapeIntent_Source) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7f0c9ff818b88a9a, []int{0, 0}
}

// Asks to begin scraping process from specific source
type ScrapeIntent struct {
	// Intent ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Indicator from where to scrape data
	Source               ScrapeIntent_Source `protobuf:"varint,2,opt,name=source,proto3,enum=scraper.ScrapeIntent_Source" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ScrapeIntent) Reset()         { *m = ScrapeIntent{} }
func (m *ScrapeIntent) String() string { return proto.CompactTextString(m) }
func (*ScrapeIntent) ProtoMessage()    {}
func (*ScrapeIntent) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f0c9ff818b88a9a, []int{0}
}

func (m *ScrapeIntent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScrapeIntent.Unmarshal(m, b)
}
func (m *ScrapeIntent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScrapeIntent.Marshal(b, m, deterministic)
}
func (m *ScrapeIntent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScrapeIntent.Merge(m, src)
}
func (m *ScrapeIntent) XXX_Size() int {
	return xxx_messageInfo_ScrapeIntent.Size(m)
}
func (m *ScrapeIntent) XXX_DiscardUnknown() {
	xxx_messageInfo_ScrapeIntent.DiscardUnknown(m)
}

var xxx_messageInfo_ScrapeIntent proto.InternalMessageInfo

func (m *ScrapeIntent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ScrapeIntent) GetSource() ScrapeIntent_Source {
	if m != nil {
		return m.Source
	}
	return ScrapeIntent_UNKNOWN
}

func init() {
	proto.RegisterEnum("scraper.ScrapeIntent_Source", ScrapeIntent_Source_name, ScrapeIntent_Source_value)
	proto.RegisterType((*ScrapeIntent)(nil), "scraper.ScrapeIntent")
}

func init() { proto.RegisterFile("scraper/intent.proto", fileDescriptor_7f0c9ff818b88a9a) }

var fileDescriptor_7f0c9ff818b88a9a = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4e, 0x2e, 0x4a,
	0x2c, 0x48, 0x2d, 0xd2, 0xcf, 0xcc, 0x2b, 0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x87, 0x8a, 0x2a, 0x95, 0x71, 0xf1, 0x04, 0x83, 0x99, 0x9e, 0x60, 0x69, 0x21, 0x3e,
	0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x13,
	0x2e, 0xb6, 0xe2, 0xfc, 0xd2, 0xa2, 0xe4, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x19,
	0x3d, 0xa8, 0x4e, 0x3d, 0x64, 0x6d, 0x7a, 0xc1, 0x60, 0x35, 0x41, 0x50, 0xb5, 0x4a, 0x0a, 0x5c,
	0x6c, 0x10, 0x11, 0x21, 0x6e, 0x2e, 0xf6, 0x50, 0x3f, 0x6f, 0x3f, 0xff, 0x70, 0x3f, 0x01, 0x06,
	0x21, 0x4e, 0x2e, 0x56, 0x47, 0x3f, 0x4f, 0x17, 0x27, 0x01, 0xc6, 0x24, 0x36, 0xb0, 0x3b, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x42, 0x60, 0x4b, 0x9f, 0x00, 0x00, 0x00,
}
