// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scraper/task.proto

package scraper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// External DB where an anime info resides
type Task_Source int32

const (
	Task_ANIDB Task_Source = 0
)

var Task_Source_name = map[int32]string{
	0: "ANIDB",
}

var Task_Source_value = map[string]int32{
	"ANIDB": 0,
}

func (x Task_Source) String() string {
	return proto.EnumName(Task_Source_name, int32(x))
}

func (Task_Source) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_19f3dda2b32e0329, []int{0, 0}
}

// Represents a task for anime pages scraping
type Task struct {
	// Task ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// External DB from where to scrape info
	Source Task_Source `protobuf:"varint,2,opt,name=source,proto3,enum=scraper.Task_Source" json:"source,omitempty"`
	// Schedule IDs for each anime ID
	ScheduleIds []int32 `protobuf:"zigzag32,3,rep,packed,name=schedule_ids,json=scheduleIds,proto3" json:"schedule_ids,omitempty"`
	// Anime ID's to scrape
	AnimeIds             []int32  `protobuf:"zigzag32,4,rep,packed,name=anime_ids,json=animeIds,proto3" json:"anime_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_19f3dda2b32e0329, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetSource() Task_Source {
	if m != nil {
		return m.Source
	}
	return Task_ANIDB
}

func (m *Task) GetScheduleIds() []int32 {
	if m != nil {
		return m.ScheduleIds
	}
	return nil
}

func (m *Task) GetAnimeIds() []int32 {
	if m != nil {
		return m.AnimeIds
	}
	return nil
}

// Intermediate result of a parse task
type TaskYield struct {
	// ID of the related task
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// ID of the schedule
	ScheduleId int32 `protobuf:"zigzag32,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	// Parsed anime entity
	Anime                *Anime   `protobuf:"bytes,3,opt,name=anime,proto3" json:"anime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskYield) Reset()         { *m = TaskYield{} }
func (m *TaskYield) String() string { return proto.CompactTextString(m) }
func (*TaskYield) ProtoMessage()    {}
func (*TaskYield) Descriptor() ([]byte, []int) {
	return fileDescriptor_19f3dda2b32e0329, []int{1}
}

func (m *TaskYield) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskYield.Unmarshal(m, b)
}
func (m *TaskYield) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskYield.Marshal(b, m, deterministic)
}
func (m *TaskYield) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskYield.Merge(m, src)
}
func (m *TaskYield) XXX_Size() int {
	return xxx_messageInfo_TaskYield.Size(m)
}
func (m *TaskYield) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskYield.DiscardUnknown(m)
}

var xxx_messageInfo_TaskYield proto.InternalMessageInfo

func (m *TaskYield) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *TaskYield) GetScheduleId() int32 {
	if m != nil {
		return m.ScheduleId
	}
	return 0
}

func (m *TaskYield) GetAnime() *Anime {
	if m != nil {
		return m.Anime
	}
	return nil
}

// Signals that a task has been finished
type TaskFinish struct {
	// ID of the related task
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskFinish) Reset()         { *m = TaskFinish{} }
func (m *TaskFinish) String() string { return proto.CompactTextString(m) }
func (*TaskFinish) ProtoMessage()    {}
func (*TaskFinish) Descriptor() ([]byte, []int) {
	return fileDescriptor_19f3dda2b32e0329, []int{2}
}

func (m *TaskFinish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskFinish.Unmarshal(m, b)
}
func (m *TaskFinish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskFinish.Marshal(b, m, deterministic)
}
func (m *TaskFinish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskFinish.Merge(m, src)
}
func (m *TaskFinish) XXX_Size() int {
	return xxx_messageInfo_TaskFinish.Size(m)
}
func (m *TaskFinish) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskFinish.DiscardUnknown(m)
}

var xxx_messageInfo_TaskFinish proto.InternalMessageInfo

func (m *TaskFinish) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func init() {
	proto.RegisterEnum("scraper.Task_Source", Task_Source_name, Task_Source_value)
	proto.RegisterType((*Task)(nil), "scraper.Task")
	proto.RegisterType((*TaskYield)(nil), "scraper.TaskYield")
	proto.RegisterType((*TaskFinish)(nil), "scraper.TaskFinish")
}

func init() { proto.RegisterFile("scraper/task.proto", fileDescriptor_19f3dda2b32e0329) }

var fileDescriptor_19f3dda2b32e0329 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0xa4, 0x4d, 0xcd, 0x44, 0x82, 0x9d, 0x0a, 0x06, 0x3d, 0x18, 0x83, 0x42, 0x0e,
	0x12, 0xa1, 0x3e, 0x41, 0x45, 0x84, 0x5c, 0x3c, 0xac, 0x5e, 0x3c, 0x95, 0x98, 0x5d, 0xe8, 0x92,
	0xda, 0x94, 0x9d, 0xf6, 0x61, 0x7c, 0x5b, 0xd9, 0x49, 0x1a, 0xbd, 0xf4, 0xb8, 0xff, 0x37, 0xbb,
	0xdf, 0xfc, 0x0b, 0x48, 0xb5, 0xad, 0xb6, 0xda, 0x3e, 0xee, 0x2a, 0x6a, 0x8a, 0xad, 0x6d, 0x77,
	0x2d, 0x4e, 0xfa, 0xec, 0x6a, 0x76, 0x80, 0xd5, 0xc6, 0x7c, 0xeb, 0x8e, 0x66, 0x3f, 0x02, 0x46,
	0x1f, 0x15, 0x35, 0x18, 0x83, 0x67, 0x54, 0x22, 0x52, 0x91, 0x87, 0xd2, 0x33, 0x0a, 0x1f, 0x20,
	0xa0, 0x76, 0x6f, 0x6b, 0x9d, 0x78, 0xa9, 0xc8, 0xe3, 0xf9, 0x45, 0xd1, 0x5f, 0x2f, 0xdc, 0x78,
	0xf1, 0xce, 0x4c, 0xf6, 0x33, 0x78, 0x0b, 0x67, 0x54, 0xaf, 0xb4, 0xda, 0xaf, 0xf5, 0xd2, 0x28,
	0x4a, 0xfc, 0xd4, 0xcf, 0xa7, 0x32, 0x3a, 0x64, 0xa5, 0x22, 0xbc, 0x86, 0x90, 0xc5, 0xcc, 0x47,
	0xcc, 0x4f, 0x39, 0x28, 0x15, 0x65, 0x33, 0x08, 0xba, 0x17, 0x31, 0x84, 0xf1, 0xe2, 0xad, 0x7c,
	0x79, 0x3e, 0x3f, 0xc9, 0x1a, 0x08, 0x9d, 0xeb, 0xd3, 0xe8, 0xb5, 0xc2, 0x4b, 0x98, 0xb8, 0x52,
	0xcb, 0x61, 0xc9, 0xc0, 0x1d, 0x4b, 0x85, 0x37, 0x10, 0xfd, 0x53, 0xf3, 0xb6, 0x53, 0x09, 0x7f,
	0x66, 0xbc, 0x83, 0x31, 0x7b, 0x12, 0x3f, 0x15, 0x79, 0x34, 0x8f, 0x87, 0x22, 0x0b, 0x97, 0xca,
	0x0e, 0x66, 0xf7, 0x00, 0x4e, 0xf6, 0x6a, 0x36, 0x86, 0x56, 0x47, 0x6d, 0x5f, 0x01, 0x7f, 0xdb,
	0xd3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17, 0xb1, 0xb6, 0xc4, 0x6a, 0x01, 0x00, 0x00,
}
