// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scraping/intent.proto

package scraping

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	common "satelit-project/satelit-scraper/proto/common"
	data "satelit-project/satelit-scraper/proto/data"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Asks to begin scraping process from specific source
type ScrapeIntent struct {
	// Intent ID
	Id *common.UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Indicator from where to scrape data
	Source               data.Source `protobuf:"varint,2,opt,name=source,proto3,enum=data.Source" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ScrapeIntent) Reset()         { *m = ScrapeIntent{} }
func (m *ScrapeIntent) String() string { return proto.CompactTextString(m) }
func (*ScrapeIntent) ProtoMessage()    {}
func (*ScrapeIntent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1599d9bfe3cd80, []int{0}
}

func (m *ScrapeIntent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScrapeIntent.Unmarshal(m, b)
}
func (m *ScrapeIntent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScrapeIntent.Marshal(b, m, deterministic)
}
func (m *ScrapeIntent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScrapeIntent.Merge(m, src)
}
func (m *ScrapeIntent) XXX_Size() int {
	return xxx_messageInfo_ScrapeIntent.Size(m)
}
func (m *ScrapeIntent) XXX_DiscardUnknown() {
	xxx_messageInfo_ScrapeIntent.DiscardUnknown(m)
}

var xxx_messageInfo_ScrapeIntent proto.InternalMessageInfo

func (m *ScrapeIntent) GetId() *common.UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ScrapeIntent) GetSource() data.Source {
	if m != nil {
		return m.Source
	}
	return data.Source_UNKNOWN
}

type ScrapeIntentResult struct {
	// ID of an intent that was used to initiate data scraping
	Id *common.UUID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Wherever there's more data to scrape
	MayContinue          bool     `protobuf:"varint,2,opt,name=may_continue,json=mayContinue,proto3" json:"may_continue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScrapeIntentResult) Reset()         { *m = ScrapeIntentResult{} }
func (m *ScrapeIntentResult) String() string { return proto.CompactTextString(m) }
func (*ScrapeIntentResult) ProtoMessage()    {}
func (*ScrapeIntentResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac1599d9bfe3cd80, []int{1}
}

func (m *ScrapeIntentResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScrapeIntentResult.Unmarshal(m, b)
}
func (m *ScrapeIntentResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScrapeIntentResult.Marshal(b, m, deterministic)
}
func (m *ScrapeIntentResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScrapeIntentResult.Merge(m, src)
}
func (m *ScrapeIntentResult) XXX_Size() int {
	return xxx_messageInfo_ScrapeIntentResult.Size(m)
}
func (m *ScrapeIntentResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ScrapeIntentResult.DiscardUnknown(m)
}

var xxx_messageInfo_ScrapeIntentResult proto.InternalMessageInfo

func (m *ScrapeIntentResult) GetId() *common.UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ScrapeIntentResult) GetMayContinue() bool {
	if m != nil {
		return m.MayContinue
	}
	return false
}

func init() {
	proto.RegisterType((*ScrapeIntent)(nil), "scraping.ScrapeIntent")
	proto.RegisterType((*ScrapeIntentResult)(nil), "scraping.ScrapeIntentResult")
}

func init() { proto.RegisterFile("scraping/intent.proto", fileDescriptor_ac1599d9bfe3cd80) }

var fileDescriptor_ac1599d9bfe3cd80 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8e, 0xb1, 0xaa, 0x83, 0x30,
	0x18, 0x46, 0xd1, 0x41, 0xe4, 0x57, 0x2e, 0x18, 0xb8, 0x20, 0x4e, 0x5e, 0xb9, 0x83, 0x53, 0x04,
	0xfb, 0x08, 0xed, 0xe2, 0x56, 0x22, 0xce, 0x25, 0x4d, 0x42, 0x09, 0x34, 0x89, 0x68, 0x32, 0xf8,
	0xf6, 0xc5, 0xc4, 0x42, 0xa7, 0xae, 0xe7, 0xe3, 0x1c, 0x3e, 0xf8, 0x5d, 0xd9, 0x42, 0x67, 0xa9,
	0x1f, 0x9d, 0xd4, 0x56, 0x68, 0x8b, 0xe7, 0xc5, 0x58, 0x83, 0xd2, 0x37, 0xae, 0x0a, 0x66, 0x94,
	0x32, 0xba, 0x73, 0x4e, 0xf2, 0x30, 0x56, 0x05, 0xa7, 0x96, 0x76, 0xab, 0x71, 0x0b, 0x13, 0x01,
	0x35, 0x57, 0xc8, 0xc7, 0xdd, 0x10, 0x83, 0xaf, 0xa0, 0x0a, 0x62, 0xc9, 0xcb, 0xa8, 0x8e, 0xda,
	0xac, 0x07, 0xec, 0xdd, 0x69, 0x1a, 0x2e, 0x24, 0x96, 0x1c, 0xfd, 0x43, 0x12, 0xdc, 0x32, 0xae,
	0xa3, 0xf6, 0xa7, 0xcf, 0xf1, 0xde, 0xc3, 0xa3, 0x67, 0xe4, 0xd8, 0x9a, 0x11, 0xd0, 0x67, 0x91,
	0x88, 0xd5, 0x3d, 0xbf, 0x77, 0xff, 0x20, 0x57, 0x74, 0xbb, 0x31, 0xa3, 0xad, 0xd4, 0x2e, 0xd4,
	0x53, 0x92, 0x29, 0xba, 0x9d, 0x0f, 0x74, 0x4f, 0xfc, 0xdb, 0xd3, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0x46, 0x70, 0x37, 0x5e, 0xf6, 0x00, 0x00, 0x00,
}
