// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scraping/service.proto

package scraping

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("scraping/service.proto", fileDescriptor_25b1fc1f20cefb19) }

var fileDescriptor_25b1fc1f20cefb19 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0xf1, 0x22, 0x32, 0xea, 0x1e, 0x52, 0xed, 0x21, 0xfa, 0x0c, 0x29, 0xd4, 0x9b, 0x78,
	0x5b, 0x56, 0xf0, 0x6a, 0x04, 0xf1, 0x98, 0x5d, 0xc7, 0x1a, 0x36, 0x9b, 0x84, 0x64, 0x56, 0xf0,
	0xf9, 0x7c, 0x31, 0x49, 0xd2, 0x54, 0x0a, 0xf5, 0x38, 0xbf, 0xef, 0xcf, 0xc0, 0x07, 0x6d, 0xdc,
	0x05, 0xe5, 0xb5, 0x1d, 0xba, 0x88, 0xe1, 0x4b, 0xef, 0x50, 0xf8, 0xe0, 0xc8, 0xb1, 0xb3, 0xca,
	0xf9, 0xcd, 0xe0, 0xdc, 0x60, 0xb0, 0xcb, 0x7c, 0x7b, 0xfc, 0xe8, 0xf0, 0xe0, 0xe9, 0xbb, 0xd8,
	0xf8, 0xf5, 0x14, 0xd7, 0x96, 0xd0, 0xd2, 0x88, 0x9b, 0x09, 0x93, 0x8a, 0xfb, 0x02, 0xfb, 0x57,
	0x58, 0xc9, 0x84, 0x31, 0xc8, 0xf2, 0x8a, 0x6d, 0xe0, 0x52, 0x92, 0x0a, 0x24, 0x47, 0x37, 0x6b,
	0x45, 0x0d, 0x8a, 0x62, 0x7d, 0xca, 0xad, 0xfc, 0x76, 0x99, 0x3f, 0x63, 0x3c, 0x1a, 0xea, 0x7f,
	0x4e, 0xa0, 0x19, 0x9b, 0x5f, 0x54, 0xdc, 0xc7, 0x5a, 0xdf, 0x03, 0xac, 0x03, 0x2a, 0xc2, 0x44,
	0xd9, 0xd5, 0x5f, 0x47, 0xba, 0x8b, 0xc2, 0x57, 0x73, 0xca, 0xee, 0xe1, 0xfc, 0x4d, 0xa3, 0x79,
	0x2f, 0xd5, 0xac, 0x99, 0xcb, 0x59, 0xe2, 0xad, 0x28, 0x93, 0x88, 0x3a, 0x89, 0xd8, 0xa4, 0x49,
	0xd8, 0x03, 0x5c, 0xac, 0xdd, 0xc1, 0x1b, 0x5c, 0xfe, 0xf8, 0xa8, 0xad, 0x8e, 0x9f, 0xff, 0xa5,
	0xb7, 0xa7, 0xf9, 0xbe, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x07, 0xf2, 0x81, 0x1d, 0x92, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ScraperServiceClient is the client API for ScraperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScraperServiceClient interface {
	// Starts web scraping and returns result of the operation when finished
	StartScraping(ctx context.Context, in *ScrapeIntent, opts ...grpc.CallOption) (*ScrapeIntentResult, error)
}

type scraperServiceClient struct {
	cc *grpc.ClientConn
}

func NewScraperServiceClient(cc *grpc.ClientConn) ScraperServiceClient {
	return &scraperServiceClient{cc}
}

func (c *scraperServiceClient) StartScraping(ctx context.Context, in *ScrapeIntent, opts ...grpc.CallOption) (*ScrapeIntentResult, error) {
	out := new(ScrapeIntentResult)
	err := c.cc.Invoke(ctx, "/scraping.ScraperService/StartScraping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScraperServiceServer is the server API for ScraperService service.
type ScraperServiceServer interface {
	// Starts web scraping and returns result of the operation when finished
	StartScraping(context.Context, *ScrapeIntent) (*ScrapeIntentResult, error)
}

// UnimplementedScraperServiceServer can be embedded to have forward compatible implementations.
type UnimplementedScraperServiceServer struct {
}

func (*UnimplementedScraperServiceServer) StartScraping(ctx context.Context, req *ScrapeIntent) (*ScrapeIntentResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartScraping not implemented")
}

func RegisterScraperServiceServer(s *grpc.Server, srv ScraperServiceServer) {
	s.RegisterService(&_ScraperService_serviceDesc, srv)
}

func _ScraperService_StartScraping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrapeIntent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperServiceServer).StartScraping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraping.ScraperService/StartScraping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperServiceServer).StartScraping(ctx, req.(*ScrapeIntent))
	}
	return interceptor(ctx, in, info, handler)
}

var _ScraperService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scraping.ScraperService",
	HandlerType: (*ScraperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartScraping",
			Handler:    _ScraperService_StartScraping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scraping/service.proto",
}

// ScraperTasksServiceClient is the client API for ScraperTasksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScraperTasksServiceClient interface {
	// Creates new scraping task and returns info about target to scrape
	CreateTask(ctx context.Context, in *TaskCreate, opts ...grpc.CallOption) (*Task, error)
	// Reports that an atomic piece of data has been scraped
	YieldResult(ctx context.Context, in *TaskYield, opts ...grpc.CallOption) (*empty.Empty, error)
	// Reports that scraping has finished and no more work will be done
	CompleteTask(ctx context.Context, in *TaskFinish, opts ...grpc.CallOption) (*empty.Empty, error)
}

type scraperTasksServiceClient struct {
	cc *grpc.ClientConn
}

func NewScraperTasksServiceClient(cc *grpc.ClientConn) ScraperTasksServiceClient {
	return &scraperTasksServiceClient{cc}
}

func (c *scraperTasksServiceClient) CreateTask(ctx context.Context, in *TaskCreate, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, "/scraping.ScraperTasksService/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperTasksServiceClient) YieldResult(ctx context.Context, in *TaskYield, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/scraping.ScraperTasksService/YieldResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperTasksServiceClient) CompleteTask(ctx context.Context, in *TaskFinish, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/scraping.ScraperTasksService/CompleteTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScraperTasksServiceServer is the server API for ScraperTasksService service.
type ScraperTasksServiceServer interface {
	// Creates new scraping task and returns info about target to scrape
	CreateTask(context.Context, *TaskCreate) (*Task, error)
	// Reports that an atomic piece of data has been scraped
	YieldResult(context.Context, *TaskYield) (*empty.Empty, error)
	// Reports that scraping has finished and no more work will be done
	CompleteTask(context.Context, *TaskFinish) (*empty.Empty, error)
}

// UnimplementedScraperTasksServiceServer can be embedded to have forward compatible implementations.
type UnimplementedScraperTasksServiceServer struct {
}

func (*UnimplementedScraperTasksServiceServer) CreateTask(ctx context.Context, req *TaskCreate) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (*UnimplementedScraperTasksServiceServer) YieldResult(ctx context.Context, req *TaskYield) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method YieldResult not implemented")
}
func (*UnimplementedScraperTasksServiceServer) CompleteTask(ctx context.Context, req *TaskFinish) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteTask not implemented")
}

func RegisterScraperTasksServiceServer(s *grpc.Server, srv ScraperTasksServiceServer) {
	s.RegisterService(&_ScraperTasksService_serviceDesc, srv)
}

func _ScraperTasksService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperTasksServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraping.ScraperTasksService/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperTasksServiceServer).CreateTask(ctx, req.(*TaskCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperTasksService_YieldResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskYield)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperTasksServiceServer).YieldResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraping.ScraperTasksService/YieldResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperTasksServiceServer).YieldResult(ctx, req.(*TaskYield))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperTasksService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskFinish)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperTasksServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scraping.ScraperTasksService/CompleteTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperTasksServiceServer).CompleteTask(ctx, req.(*TaskFinish))
	}
	return interceptor(ctx, in, info, handler)
}

var _ScraperTasksService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scraping.ScraperTasksService",
	HandlerType: (*ScraperTasksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _ScraperTasksService_CreateTask_Handler,
		},
		{
			MethodName: "YieldResult",
			Handler:    _ScraperTasksService_YieldResult_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _ScraperTasksService_CompleteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scraping/service.proto",
}
