// Code generated by protoc-gen-go. DO NOT EDIT.
// source: import/intent.proto

package _import

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	data "satelit-project/satelit-scraper/pkg/proto/data"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Asks to import anime titles index and schedule new titles for scraping
type ImportIntent struct {
	// Intent ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Represents an external DB from where anime titles index should be imported
	Source data.Source `protobuf:"varint,2,opt,name=source,proto3,enum=data.Source" json:"source,omitempty"`
	// URL of anime titles dump location
	DumpUrl string `protobuf:"bytes,3,opt,name=dump_url,json=dumpUrl,proto3" json:"dump_url,omitempty"`
	// Identifiers of anime titles that should be re-imported
	ReimportIds          []int32  `protobuf:"zigzag32,4,rep,packed,name=reimport_ids,json=reimportIds,proto3" json:"reimport_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportIntent) Reset()         { *m = ImportIntent{} }
func (m *ImportIntent) String() string { return proto.CompactTextString(m) }
func (*ImportIntent) ProtoMessage()    {}
func (*ImportIntent) Descriptor() ([]byte, []int) {
	return fileDescriptor_93c332ae50efc1f8, []int{0}
}

func (m *ImportIntent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportIntent.Unmarshal(m, b)
}
func (m *ImportIntent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportIntent.Marshal(b, m, deterministic)
}
func (m *ImportIntent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportIntent.Merge(m, src)
}
func (m *ImportIntent) XXX_Size() int {
	return xxx_messageInfo_ImportIntent.Size(m)
}
func (m *ImportIntent) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportIntent.DiscardUnknown(m)
}

var xxx_messageInfo_ImportIntent proto.InternalMessageInfo

func (m *ImportIntent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ImportIntent) GetSource() data.Source {
	if m != nil {
		return m.Source
	}
	return data.Source_UNKNOWN
}

func (m *ImportIntent) GetDumpUrl() string {
	if m != nil {
		return m.DumpUrl
	}
	return ""
}

func (m *ImportIntent) GetReimportIds() []int32 {
	if m != nil {
		return m.ReimportIds
	}
	return nil
}

type ImportIntentResult struct {
	// Intent ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// IDs of anime titles that was not imported
	SkippedIds           []int32  `protobuf:"zigzag32,2,rep,packed,name=skipped_ids,json=skippedIds,proto3" json:"skipped_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportIntentResult) Reset()         { *m = ImportIntentResult{} }
func (m *ImportIntentResult) String() string { return proto.CompactTextString(m) }
func (*ImportIntentResult) ProtoMessage()    {}
func (*ImportIntentResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_93c332ae50efc1f8, []int{1}
}

func (m *ImportIntentResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportIntentResult.Unmarshal(m, b)
}
func (m *ImportIntentResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportIntentResult.Marshal(b, m, deterministic)
}
func (m *ImportIntentResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportIntentResult.Merge(m, src)
}
func (m *ImportIntentResult) XXX_Size() int {
	return xxx_messageInfo_ImportIntentResult.Size(m)
}
func (m *ImportIntentResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportIntentResult.DiscardUnknown(m)
}

var xxx_messageInfo_ImportIntentResult proto.InternalMessageInfo

func (m *ImportIntentResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ImportIntentResult) GetSkippedIds() []int32 {
	if m != nil {
		return m.SkippedIds
	}
	return nil
}

func init() {
	proto.RegisterType((*ImportIntent)(nil), "import.ImportIntent")
	proto.RegisterType((*ImportIntentResult)(nil), "import.ImportIntentResult")
}

func init() { proto.RegisterFile("import/intent.proto", fileDescriptor_93c332ae50efc1f8) }

var fileDescriptor_93c332ae50efc1f8 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xbf, 0x4a, 0xc7, 0x30,
	0x14, 0x85, 0x49, 0x2a, 0x55, 0x6f, 0x4b, 0xa1, 0x71, 0x89, 0x2e, 0xd6, 0xe2, 0xd0, 0xa9, 0x05,
	0x7d, 0x06, 0x87, 0xac, 0x11, 0xe7, 0x52, 0xbd, 0x19, 0x82, 0x6d, 0x13, 0xf2, 0xe7, 0x05, 0x7c,
	0x72, 0x69, 0x52, 0x41, 0xf8, 0x8d, 0xf7, 0x3b, 0x9c, 0xc3, 0x77, 0xe1, 0x4e, 0x6f, 0xd6, 0xb8,
	0x30, 0xe9, 0x3d, 0xa8, 0x3d, 0x8c, 0xd6, 0x99, 0x60, 0x58, 0x99, 0xe1, 0x43, 0x8b, 0x4b, 0x58,
	0x26, 0x6f, 0xa2, 0xfb, 0x52, 0x39, 0xea, 0x7f, 0x08, 0xd4, 0x22, 0xa5, 0x22, 0x35, 0x58, 0x03,
	0x54, 0x23, 0x27, 0x1d, 0x19, 0x6e, 0x25, 0xd5, 0xc8, 0x9e, 0xa1, 0xcc, 0x05, 0x4e, 0x3b, 0x32,
	0x34, 0x2f, 0xf5, 0x78, 0x8c, 0x8c, 0xef, 0x89, 0xc9, 0x33, 0x63, 0xf7, 0x70, 0x83, 0x71, 0xb3,
	0x73, 0x74, 0x2b, 0x2f, 0x52, 0xf7, 0xfa, 0xb8, 0x3f, 0xdc, 0xca, 0x9e, 0xa0, 0x76, 0x2a, 0x0b,
	0xcc, 0x1a, 0x3d, 0xbf, 0xea, 0x8a, 0xa1, 0x95, 0xd5, 0x1f, 0x13, 0xe8, 0xfb, 0x37, 0x60, 0xff,
	0x1d, 0xa4, 0xf2, 0x71, 0xbd, 0x34, 0x79, 0x84, 0xca, 0x7f, 0x6b, 0x6b, 0x15, 0xa6, 0x1d, 0x9a,
	0x76, 0xe0, 0x44, 0x02, 0xfd, 0x67, 0x99, 0x5e, 0x7a, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x88,
	0x68, 0x6c, 0x01, 0x04, 0x01, 0x00, 0x00,
}
