// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data/source.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// External data source
type Source int32

const (
	Source_UNKNOWN Source = 0
	Source_ANIDB   Source = 1
)

var Source_name = map[int32]string{
	0: "UNKNOWN",
	1: "ANIDB",
}

var Source_value = map[string]int32{
	"UNKNOWN": 0,
	"ANIDB":   1,
}

func (x Source) String() string {
	return proto.EnumName(Source_name, int32(x))
}

func (Source) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5d07b50692df356, []int{0}
}

func init() {
	proto.RegisterEnum("data.Source", Source_name, Source_value)
}

func init() { proto.RegisterFile("data/source.proto", fileDescriptor_d5d07b50692df356) }

var fileDescriptor_d5d07b50692df356 = []byte{
	// 83 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x49, 0x2c, 0x49,
	0xd4, 0x2f, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01,
	0x09, 0x69, 0x29, 0x70, 0xb1, 0x05, 0x83, 0x45, 0x85, 0xb8, 0xb9, 0xd8, 0x43, 0xfd, 0xbc, 0xfd,
	0xfc, 0xc3, 0xfd, 0x04, 0x18, 0x84, 0x38, 0xb9, 0x58, 0x1d, 0xfd, 0x3c, 0x5d, 0x9c, 0x04, 0x18,
	0x93, 0xd8, 0xc0, 0xca, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x73, 0xff, 0x27, 0xaa, 0x43,
	0x00, 0x00, 0x00,
}
